import { db, itemsTable } from "../src/db/index.js";

const realWorldElectronicsCatalog = [
  {
    partNumber: "ESP32-WROOM-32E-N4",
    name: "Espressif ESP32-WROOM-32E 4MB Flash Module",
    description: "Espressif 240MHz dual-core Xtensa 32-bit LX6 with integrated 4MB SPI flash and PCB trace antenna.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Espressif Systems",
      architecture: "Xtensa Dual-Core 32-bit LX6",
      clockSpeed: "240 MHz",
      flashSize: "4 MB",
      sramSize: "520 KB",
      wireless: "Wi-Fi 802.11 b/g/n + Bluetooth 4.2 / BLE",
      voltage: "3.0V - 3.6V",
      packageFootprint: "SMD Module 38-Pin (18x25.5mm)",
    },
  },
  {
    partNumber: "ESP32-WROOM-32E-N8",
    name: "Espressif ESP32-WROOM-32E 8MB Flash Module",
    description: "Espressif 240MHz dual-core Xtensa 32-bit LX6 with extended 8MB SPI flash for larger OTA partitions.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Espressif Systems",
      architecture: "Xtensa Dual-Core 32-bit LX6",
      clockSpeed: "240 MHz",
      flashSize: "8 MB",
      sramSize: "520 KB",
      wireless: "Wi-Fi 802.11 b/g/n + Bluetooth 4.2 / BLE",
      voltage: "3.0V - 3.6V",
      packageFootprint: "SMD Module 38-Pin (18x25.5mm)",
    },
  },
  {
    partNumber: "ESP32-S3-WROOM-1-N8R8",
    name: "Espressif ESP32-S3 AI Vector MCU 8MB Flash 8MB PSRAM",
    description: "Espressif dual-core Xtensa LX7 MCU with vector instructions for AI acceleration, 8MB Quad SPI Flash and 8MB Octal PSRAM.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Espressif Systems",
      architecture: "Xtensa Dual-Core 32-bit LX7 with Vector Extensions",
      clockSpeed: "240 MHz",
      flashSize: "8 MB",
      psramSize: "8 MB (Octal)",
      sramSize: "512 KB",
      wireless: "Wi-Fi 802.11 b/g/n (2.4GHz) + Bluetooth 5 (LE)",
      packageFootprint: "SMD Module 41-Pin (18x25.5mm)",
    },
  },
  {
    partNumber: "ESP32-C3-WROOM-02-N4",
    name: "Espressif ESP32-C3 RISC-V 32-bit Single-Core MCU",
    description: "Espressif cost-optimized 160MHz single-core 32-bit RISC-V microcontroller with 4MB embedded Flash.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Espressif Systems",
      architecture: "32-bit RISC-V Single-Core (RV32IMC)",
      clockSpeed: "160 MHz",
      flashSize: "4 MB",
      sramSize: "400 KB",
      wireless: "Wi-Fi 802.11 b/g/n + Bluetooth 5 (LE)",
      packageFootprint: "SMD Module 18-Pin (18x20mm)",
    },
  },
  {
    partNumber: "STM32F103C8T6",
    name: "STMicroelectronics STM32F103C8T6 ARM Cortex-M3 72MHz MCU",
    description: "STMicroelectronics mainstream performance line ARM Cortex-M3 32-bit MCU with 64KB Flash in LQFP-48.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      core: "ARM Cortex-M3",
      clockSpeed: "72 MHz",
      flashMemory: "64 KB",
      sram: "20 KB",
      interfaces: "2x SPI, 2x I2C, 3x USART, 1x USB 2.0 Full-Speed, 1x CAN 2.0B",
      packageFootprint: "LQFP-48 (7x7mm)",
      voltage: "2.0V - 3.6V",
    },
  },
  {
    partNumber: "STM32F401RET6",
    name: "STMicroelectronics STM32F401RE ARM Cortex-M4 84MHz MCU",
    description: "STMicroelectronics dynamic efficiency line ARM Cortex-M4 MCU with FPU, 512KB Flash, 96KB SRAM in LQFP-64.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      core: "ARM Cortex-M4 with FPU",
      clockSpeed: "84 MHz",
      flashMemory: "512 KB",
      sram: "96 KB",
      interfaces: "3x SPI, 3x I2C, 3x USART, 1x USB 2.0 OTG FS",
      packageFootprint: "LQFP-64 (10x10mm)",
      voltage: "1.7V - 3.6V",
    },
  },
  {
    partNumber: "STM32F411CEU6",
    name: "STMicroelectronics STM32F411CE ARM Cortex-M4 100MHz MCU",
    description: "STMicroelectronics high performance ARM Cortex-M4 MCU with 512KB Flash and 128KB SRAM in compact UFQFPN-48.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      core: "ARM Cortex-M4 with FPU",
      clockSpeed: "100 MHz",
      flashMemory: "512 KB",
      sram: "128 KB",
      packageFootprint: "UFQFPN-48 (7x7mm)",
      voltage: "1.7V - 3.6V",
    },
  },
  {
    partNumber: "ATMEGA328P-PU",
    name: "Microchip ATmega328P DIP-28 8-Bit AVR Microcontroller",
    description: "Microchip 20MHz 8-bit AVR RISC microcontroller with 32KB ISP Flash memory in DIP-28 through-hole package.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Microchip Technology",
      architecture: "8-bit AVR RISC",
      clockSpeed: "20 MHz",
      flashMemory: "32 KB",
      sram: "2 KB",
      eeprom: "1 KB",
      gpioCount: 23,
      adcChannels: 6,
      packageFootprint: "DIP-28",
      voltage: "1.8V - 5.5V",
    },
  },
  {
    partNumber: "ATMEGA328P-AU",
    name: "Microchip ATmega328P TQFP-32 8-Bit AVR Microcontroller",
    description: "Microchip 20MHz 8-bit AVR RISC microcontroller with 32KB ISP Flash in compact 32-lead surface mount TQFP package.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Microchip Technology",
      architecture: "8-bit AVR RISC",
      clockSpeed: "20 MHz",
      flashMemory: "32 KB",
      sram: "2 KB",
      eeprom: "1 KB",
      gpioCount: 23,
      adcChannels: 8,
      packageFootprint: "TQFP-32 (7x7mm)",
      voltage: "1.8V - 5.5V",
    },
  },
  {
    partNumber: "RP2040",
    name: "Raspberry Pi RP2040 Dual ARM Cortex-M0+ Microcontroller",
    description: "Raspberry Pi Foundation designed 133MHz dual-core ARM Cortex-M0+ microcontroller with 264KB internal SRAM and 8 PIO state machines.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Raspberry Pi Foundation",
      cores: "Dual ARM Cortex-M0+",
      clockSpeed: "133 MHz",
      sram: "264 KB",
      pioBlocks: "2x PIO state machines (8 total)",
      interfaces: "2x UART, 2x SPI, 2x I2C, 16x PWM, USB 1.1 Host/Device",
      packageFootprint: "QFN-56 (7x7mm)",
      voltage: "1.8V - 3.3V",
    },
  },
  {
    partNumber: "RC0805FR-0710KL",
    name: "Yageo 10k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 10kΩ ±1% 0.125W.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "10k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±100 ppm/°C",
    },
  },
  {
    partNumber: "CRCW080510K0FKEA",
    name: "Vishay Dale 10k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Vishay Dale commercial thick film surface mount chip resistor 10kΩ ±1% 0.125W automotive qualified AEC-Q200.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Vishay Dale",
      resistance: "10k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±100 ppm/°C",
      qualification: "AEC-Q200",
    },
  },
  {
    partNumber: "ERJ-6GEYJ103V",
    name: "Panasonic 10k Ohm 5% 1/8W SMD Resistor 0805",
    description: "Panasonic ERJ series thick film chip resistor 10kΩ ±5% 0.125W.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Panasonic",
      resistance: "10k Ohm",
      tolerance: "±5%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±200 ppm/°C",
    },
  },
  {
    partNumber: "RC0603FR-0710KL",
    name: "Yageo 10k Ohm 1% 1/10W SMD Resistor 0603",
    description: "Yageo RC0603 series miniature thick film surface mount chip resistor 10kΩ ±1% 0.1W in 0603 package.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "10k Ohm",
      tolerance: "±1%",
      powerRating: "0.1W (1/10W)",
      packageFootprint: "0603 (1608 Metric)",
      tempCoeff: "±100 ppm/°C",
    },
  },
  {
    partNumber: "MFR-25FRF52-10K",
    name: "Yageo 10k Ohm 1% 1/4W Metal Film Resistor Axial",
    description: "Yageo MFR series high precision metal film through-hole axial leaded resistor 10kΩ ±1% 0.25W.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "10k Ohm",
      tolerance: "±1%",
      powerRating: "0.25W (1/4W)",
      packageFootprint: "Axial Leaded (DO-41 size)",
      tempCoeff: "±50 ppm/°C",
    },
  },
  {
    partNumber: "RC0805FR-071KL",
    name: "Yageo 1k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 1kΩ ±1% 0.125W.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "1k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±100 ppm/°C",
    },
  },
  {
    partNumber: "RC0805FR-07220RL",
    name: "Yageo 220 Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 220Ω ±1% 0.125W for LED current limiting.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "220 Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "RC0805FR-074K7L",
    name: "Yageo 4.7k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 4.7kΩ ±1% 0.125W standard I2C bus pull-up.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "4.7k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "CL21B106KOQNNNE",
    name: "Samsung 10uF 16V X7R Ceramic Capacitor 0805",
    description: "Samsung Electro-Mechanics multi-layer ceramic chip capacitor (MLCC) 10µF 16V ±10% X7R.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Samsung Electro-Mechanics",
      capacitance: "10 uF",
      voltageRating: "16V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "GRM21BR71C106KE51L",
    name: "Murata 10uF 16V X7R Ceramic Capacitor 0805",
    description: "Murata GRM series multi-layer ceramic chip capacitor (MLCC) 10µF 16V ±10% X7R.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Murata Electronics",
      capacitance: "10 uF",
      voltageRating: "16V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "CC0805KRX7R9BB104",
    name: "Yageo 100nF (0.1uF) 50V X7R Ceramic Capacitor 0805",
    description: "Yageo surface mount ceramic chip capacitor 0.1µF 50V ±10% X7R for IC power rail decoupling.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      capacitance: "100 nF (0.1 uF)",
      voltageRating: "50V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "C0805C104K5RACTU",
    name: "KEMET 100nF (0.1uF) 50V X7R Ceramic Capacitor 0805",
    description: "KEMET surface mount commercial grade MLCC 0.1µF 50V ±10% X7R in 0805 package.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "KEMET",
      capacitance: "100 nF (0.1 uF)",
      voltageRating: "50V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "UVP1E101MPD",
    name: "Nichicon 100uF 25V Radial Electrolytic Capacitor",
    description: "Nichicon VP series bi-polarized aluminum electrolytic capacitor 100µF 25V 20% radial leaded.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Nichicon",
      capacitance: "100 uF",
      voltageRating: "25V DC",
      tolerance: "±20%",
      packageFootprint: "Radial Can (8x11.5mm)",
    },
  },
  {
    partNumber: "CC0805JRNPO9BN220",
    name: "Yageo 22pF 50V C0G/NP0 Ceramic Capacitor 0805",
    description: "Yageo ultra-stable C0G/NP0 dielectric ceramic capacitor 22pF 50V ±5% for 16MHz/32MHz crystal oscillators.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      capacitance: "22 pF",
      voltageRating: "50V DC",
      dielectric: "C0G / NP0",
      tolerance: "±5%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "1N4007-TP",
    name: "MCC 1N4007 1A 1000V Standard Recovery Rectifier Diode",
    description: "Micro Commercial Co standard recovery power rectifier diode 1A 1000V in axial leaded DO-41 package.",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "Micro Commercial Components (MCC)",
      diodeType: "Standard Recovery Rectifier",
      forwardCurrent: "1A",
      peakReverseVoltage: "1000V",
      packageFootprint: "DO-41 Axial",
    },
  },
  {
    partNumber: "1N4148WS-7-F",
    name: "Diodes Inc 1N4148WS 100V 300mA High-Speed Switching Diode",
    description: "Diodes Incorporated fast switching surface mount diode 100V 300mA 4ns recovery time in SOD-323.",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "Diodes Incorporated",
      diodeType: "High Speed Switching",
      reverseVoltage: "100V",
      forwardCurrent: "300mA",
      packageFootprint: "SOD-323",
    },
  },
  {
    partNumber: "B5819W-TP",
    name: "MCC 1N5819 (B5819W) 1A 40V Schottky Barrier Diode SOD-123",
    description: "Micro Commercial Co 1A 40V low forward voltage drop Schottky barrier diode in SOD-123 for reverse polarity protection.",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "Micro Commercial Components (MCC)",
      diodeType: "Schottky Barrier",
      forwardCurrent: "1A",
      reverseVoltage: "40V",
      packageFootprint: "SOD-123",
    },
  },
  {
    partNumber: "150080RS75000",
    name: "Würth Elektronik Red SMD LED 0805 Clear Lens",
    description: "Würth Elektronik WL-SMCW series red surface mount chip LED 625nm 120mcd 0805.",
    category: "LED",
    unit: "pcs",
    specifications: {
      manufacturer: "Würth Elektronik",
      color: "Red",
      dominantWavelength: "625 nm",
      forwardVoltage: "2.0V",
      forwardCurrent: "20 mA",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "150080GS75000",
    name: "Würth Elektronik Green SMD LED 0805 Clear Lens",
    description: "Würth Elektronik WL-SMCW series green surface mount chip LED 525nm 260mcd 0805.",
    category: "LED",
    unit: "pcs",
    specifications: {
      manufacturer: "Würth Elektronik",
      color: "Green",
      dominantWavelength: "525 nm",
      forwardVoltage: "3.2V",
      forwardCurrent: "20 mA",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "150080BS75000",
    name: "Würth Elektronik Blue SMD LED 0805 Clear Lens",
    description: "Würth Elektronik WL-SMCW series blue surface mount chip LED 470nm 140mcd 0805.",
    category: "LED",
    unit: "pcs",
    specifications: {
      manufacturer: "Würth Elektronik",
      color: "Blue",
      dominantWavelength: "470 nm",
      forwardVoltage: "3.2V",
      forwardCurrent: "20 mA",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "AMS1117-3.3",
    name: "Advanced Monolithic Systems AMS1117 3.3V 1A LDO Regulator",
    description: "AMS1117 series low dropout positive voltage regulator fixed 3.3V 1A output in SOT-223.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Advanced Monolithic Systems",
      regulatorType: "LDO Linear Voltage Regulator",
      outputVoltage: "3.3V Fixed",
      maxOutputCurrent: "1.0A",
      packageFootprint: "SOT-223",
    },
  },
  {
    partNumber: "AZ1117EH-3.3TRG1",
    name: "Diodes Inc AZ1117E 3.3V 1A Low Dropout Regulator",
    description: "Diodes Incorporated low dropout linear regulator 3.3V 1A with thermal shutdown in SOT-223.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Diodes Incorporated",
      outputVoltage: "3.3V Fixed",
      maxOutputCurrent: "1.0A",
      packageFootprint: "SOT-223",
    },
  },
  {
    partNumber: "LM7805CT",
    name: "Texas Instruments LM7805 5V 1.5A Positive Linear Regulator",
    description: "Texas Instruments 3-terminal positive voltage regulator 5.0V 1.5A in TO-220 package.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Texas Instruments",
      outputVoltage: "5.0V Fixed",
      maxOutputCurrent: "1.5A",
      packageFootprint: "TO-220-3",
    },
  },
  {
    partNumber: "2N7002-7-F",
    name: "Diodes Inc 2N7002 60V 115mA N-Channel MOSFET SOT-23",
    description: "Diodes Incorporated N-Channel enhancement mode field effect transistor 60V 115mA in SOT-23.",
    category: "Transistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Diodes Incorporated",
      transistorType: "N-Channel MOSFET",
      drainSourceVoltage: "60V",
      continuousDrainCurrent: "115 mA",
      packageFootprint: "SOT-23-3",
    },
  },
  {
    partNumber: "BME280",
    name: "Bosch Sensortec BME280 Temp, Humidity & Pressure Sensor",
    description: "Bosch Sensortec high precision digital environmental sensor with I2C and SPI interfaces in LGA-8 package.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Bosch Sensortec",
      measuredParameters: "Temperature, Relative Humidity, Barometric Pressure",
      humidityRange: "0% to 100% RH (±3%)",
      pressureRange: "300 to 1100 hPa (±1 hPa)",
      temperatureRange: "-40°C to 85°C (±0.5°C)",
      interface: "I2C and SPI",
      packageFootprint: "LGA-8 (2.5x2.5mm)",
    },
  },
  {
    partNumber: "BMP280",
    name: "Bosch Sensortec BMP280 Barometric Pressure & Temp Sensor",
    description: "Bosch Sensortec compact digital barometric pressure and temperature sensor with I2C/SPI interfaces.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Bosch Sensortec",
      measuredParameters: "Barometric Pressure, Temperature",
      pressureRange: "300 to 1100 hPa",
      temperatureRange: "-40°C to 85°C",
      interface: "I2C and SPI",
      packageFootprint: "LGA-8 (2.0x2.5mm)",
    },
  },
  {
    partNumber: "DHT22",
    name: "Aosong DHT22 (AM2302) Digital Temp & Humidity Sensor",
    description: "Aosong capacitive humidity and thermistor temperature sensor module with single-wire digital interface.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Aosong Electronics",
      humidityRange: "0% - 99.9% RH (±2%)",
      temperatureRange: "-40°C to 80°C (±0.5°C)",
      interface: "Single-bus custom digital protocol",
      packageFootprint: "4-Pin Module",
    },
  },
  {
    partNumber: "HC-SR04",
    name: "ElecFreaks HC-SR04 Ultrasonic Distance Sensor Module",
    description: "Standard ultrasonic ranging module with 2cm to 400cm non-contact measurement range, 5V operating voltage.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "ElecFreaks",
      range: "2cm to 400cm",
      accuracy: "3mm",
      operatingVoltage: "5V DC",
      triggerInput: "10uS TTL pulse",
      packageFootprint: "Module with 2 Transducers (45x20mm)",
    },
  },
  {
    partNumber: "HC-SR501",
    name: "PIR Motion Detector Sensor Module HC-SR501",
    description: "Passive infrared PIR motion sensor module with adjustable sensitivity and delay time for human presence detection.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      sensorType: "Pyroelectric Infrared (PIR)",
      detectionAngle: "<100 degrees cone",
      detectionRange: "Up to 7 meters",
      operatingVoltage: "4.5V - 20V DC",
      packageFootprint: "PCB Module with Fresnel Lens (32x24mm)",
    },
  },
  {
    partNumber: "DS18B20",
    name: "Maxim DS18B20 Programmable Resolution 1-Wire Digital Thermometer",
    description: "Maxim Integrated 1-Wire digital temperature sensor with 9-bit to 12-bit user-configurable resolution in TO-92.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Maxim Integrated / Analog Devices",
      tempRange: "-55°C to 125°C (±0.5°C accuracy from -10°C to +85°C)",
      interface: "1-Wire Serial Interface",
      uniqueId: "Unique 64-bit Serial Code",
      packageFootprint: "TO-92 Through-Hole",
    },
  },
  {
    partNumber: "MQ-2",
    name: "Zhengzhou Winsen MQ-2 Gas & Smoke Detection Sensor",
    description: "Winsen semiconductor gas sensor for detecting combustible gases, LPG, propane, methane, alcohol, and smoke.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Zhengzhou Winsen Electronics",
      targetGases: "LPG, i-butane, propane, methane, alcohol, hydrogen, smoke",
      heaterVoltage: "5.0V ± 0.1V",
      packageFootprint: "6-Pin Metal Cap Module",
    },
  },
  {
    partNumber: "RC522-RFID-MOD",
    name: "NXP MFRC522 13.56MHz Contactless RFID Reader Module",
    description: "NXP MFRC522 highly integrated reader/writer IC for 13.56MHz contactless communication with PCB antenna.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "NXP Semiconductors",
      frequency: "13.56 MHz (ISO/IEC 14443 A/MIFARE)",
      communicationInterface: "SPI (up to 10Mbit/s)",
      operatingVoltage: "3.3V DC",
      packageFootprint: "Module with PCB Antenna (40x60mm)",
    },
  },
  {
    partNumber: "SSD1306-0.96-OLED-I2C",
    name: "Solomon Systech SSD1306 0.96 inch 128x64 I2C OLED Display Module",
    description: "0.96-inch monochrome blue/white OLED graphic display module with built-in SSD1306 controller and I2C interface.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Solomon Systech",
      displayType: "Monochrome OLED",
      resolution: "128 x 64 Pixels",
      screenSize: "0.96 inch diagonal",
      interface: "I2C (Address 0x3C or 0x3D)",
      operatingVoltage: "3.3V - 5.0V",
      packageFootprint: "4-Pin Breakout Module (27x27mm)",
    },
  },
  {
    partNumber: "ST7789V-1.3-IPS-SPI",
    name: "Sitronix ST7789V 1.3 inch 240x240 Full-Color IPS LCD Display",
    description: "1.3-inch 240x240 RGB high-resolution IPS display with ST7789V controller and 4-wire SPI interface.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Sitronix",
      displayType: "IPS Full Color LCD (65K Colors)",
      resolution: "240 x 240 Pixels",
      interface: "4-Wire SPI",
      operatingVoltage: "3.3V DC",
      packageFootprint: "7-Pin Breakout Module",
    },
  },
  {
    partNumber: "NRF24L01P-MOD",
    name: "Nordic Semi nRF24L01+ 2.4GHz Wireless RF Transceiver Module",
    description: "Nordic Semiconductor ultra-low-power 2.4GHz ISM band wireless transceiver module with on-board PCB antenna.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Nordic Semiconductor",
      frequencyBand: "2.4 GHz to 2.5 GHz ISM",
      dataRate: "250 kbps, 1 Mbps, 2 Mbps",
      operatingVoltage: "1.9V - 3.6V (5V tolerant logic)",
      interface: "SPI (up to 10 Mbps)",
      packageFootprint: "8-Pin 2x4 Header (15x29mm)",
    },
  },
  {
    partNumber: "SX1278-LORA-433M",
    name: "Semtech SX1278 433MHz Long Range LoRa Wireless Transceiver",
    description: "Semtech SX1278 LoRa spread spectrum wireless RF communication transceiver module with SPI interface.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Semtech",
      frequency: "433 MHz (410 - 525 MHz)",
      modulation: "LoRa / FSK / GFSK / OOK",
      sensitivity: "Up to -148 dBm",
      range: "Up to 5 km (Line of sight)",
      packageFootprint: "SMD-16 (16x16mm)",
    },
  },
  {
    partNumber: "L298N-MOD",
    name: "STMicroelectronics L298N Dual Full-Bridge Motor Driver Module",
    description: "STMicroelectronics dual H-bridge motor driver module capable of driving two DC motors or one 4-wire stepper motor up to 2A per channel.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      driverType: "Dual H-Bridge Driver",
      peakCurrent: "2A per Bridge (3A non-repetitive)",
      operatingVoltage: "5V - 35V DC",
      packageFootprint: "Heatsink Module (43x43mm)",
    },
  },
  {
    partNumber: "A4988-MOD",
    name: "Allegro A4988 Microstepping Stepper Motor Driver Module",
    description: "Allegro A4988 DMOS microstepping driver with built-in translator and overcurrent protection for 3D printers and CNC machines.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Allegro MicroSystems",
      microstepResolution: "Full, 1/2, 1/4, 1/8, 1/16 step",
      outputCurrent: "Up to 2A with heatsink",
      operatingVoltage: "8V - 35V DC",
      packageFootprint: "Pololu-style 16-Pin Carrier (15x20mm)",
    },
  },
  {
    partNumber: "SG90-SERVO",
    name: "TowerPro SG90 9g Micro Analog Servo Motor 180°",
    description: "TowerPro lightweight 9g micro servo motor with nylon gears and 180 degree rotation for robotics and RC models.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "TowerPro",
      stallTorque: "1.8 kg-cm @ 4.8V",
      operatingSpeed: "0.10 sec/60 degrees",
      operatingVoltage: "4.8V - 6.0V DC",
      weight: "9 grams",
      packageFootprint: "Plastic Body (22.2x11.8x31mm)",
    },
  },
  {
    partNumber: "TP4056-TYPE-C",
    name: "NanJing Top Power TP4056 1A Li-Ion Battery Charger with Protection",
    description: "Complete constant-current/constant-voltage linear charger for single cell lithium-ion batteries with Type-C input and DW01A protection.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "NanJing Top Power ASIC Corp",
      chargeCurrent: "1.0A Programmable",
      fullChargeVoltage: "4.2V ± 1%",
      inputConnector: "USB Type-C",
      batteryProtection: "DW01A + FS8205A Dual MOSFET (Over-discharge & Over-current)",
      packageFootprint: "Module (17x28mm)",
    },
  },
  {
    partNumber: "LM2596S-ADJ-MOD",
    name: "Texas Instruments LM2596S 3A Step-Down Buck Converter Module",
    description: "TI LM2596 simple switcher 150kHz 3A step-down voltage regulator module with multi-turn potentiometer adjustment.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Texas Instruments",
      inputVoltage: "4.0V - 40V DC",
      outputVoltage: "1.25V - 37V DC (Adjustable)",
      maxCurrent: "3.0A (with heatsink)",
      switchingFrequency: "150 kHz",
      packageFootprint: "Buck Module (43x21mm)",
    },
  },
  {
    partNumber: "DS3231SN",
    name: "Maxim DS3231 High-Precision RTC with Integrated TCXO",
    description: "Maxim Integrated extremely accurate I2C real-time clock (RTC) with integrated temperature-compensated crystal oscillator (TCXO) in SO-16.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Maxim Integrated / Analog Devices",
      accuracy: "±2ppm from 0°C to +40°C (approx ±1 min/year)",
      batteryBackup: "Automatic switchover to coin cell CR2032",
      interface: "I2C (400kHz)",
      packageFootprint: "SO-16 (300mil)",
    },
  },
  {
    partNumber: "W25Q64JVSSIQ",
    name: "Winbond 64Mb (8MB) Serial NOR Flash Memory SPI 133MHz",
    description: "Winbond 64M-bit serial flash memory with dual/quad SPI in standard 8-pin SOIC 208mil package.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Winbond Electronics",
      capacity: "64 Mbit (8 MByte)",
      clockFrequency: "133 MHz (Quad-SPI up to 532 MHz equivalent)",
      voltage: "2.7V - 3.6V",
      packageFootprint: "SOIC-8 (208mil)",
    },
  },
  {
    partNumber: "TYPE-C-31-M-12",
    name: "Korean Hroparts 16-Pin USB Type-C Receptacle Hybrid SMD/THT",
    description: "Korean Hroparts 16-pin USB Type-C female connector with mid-mount SMD pins and 4 through-hole shielding retention legs.",
    category: "Connector",
    unit: "pcs",
    specifications: {
      manufacturer: "Korean Hroparts Electronics",
      connectorType: "USB Type-C Female Receptacle",
      pinCount: 16,
      currentRating: "3.0A",
      voltageRating: "20V DC",
      matingCycles: "10,000 Cycles",
      packageFootprint: "Hybrid SMD + 4 THT Shell Posts",
    },
  },
  {
    partNumber: "61304011121",
    name: "Würth Elektronik 40-Pin 2.54mm Breakaway Pin Header Male",
    description: "Würth Elektronik WR-PHD series 2.54mm pitch 40-pin single row straight through-hole male pin header strip.",
    category: "Connector",
    unit: "pcs",
    specifications: {
      manufacturer: "Würth Elektronik",
      pitch: "2.54 mm (0.1 inch)",
      numberOfPositions: 40,
      contactPlating: "Gold Plated",
      currentRating: "3.0A",
      packageFootprint: "Through-Hole Vertical",
    },
  },
  {
    partNumber: "B3F-1000",
    name: "Omron 6x6mm SPST Tactile Push Button Switch",
    description: "Omron Electronics B3F series 6x6x4.3mm miniature tactile push button switch SPST-NO through-hole.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Omron Electronics",
      switchFunction: "Momentary SPST-NO",
      operatingForce: "0.98 N (100 gf)",
      contactRating: "50 mA @ 24V DC",
      mechanicalLife: "1,000,000 Operations",
      packageFootprint: "Through-Hole 4-Pin (6.0x6.0mm)",
    },
  },
  {
    partNumber: "CH340C",
    name: "WCH CH340C USB to UART Serial Bridge IC Internal Oscillator",
    description: "Jiangsu Qinheng Microelectronics (WCH) USB to serial UART interface converter with internal clock generator in SOP-16.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "WCH (Jiangsu Qinheng Microelectronics)",
      function: "USB 2.0 Full-Speed to UART Serial Bridge",
      clockSource: "Internal Oscillator (No external crystal needed)",
      baudRate: "50 bps to 2 Mbps",
      packageFootprint: "SOP-16 (150mil)",
    },
  },
  {
    partNumber: "SRD-05VDC-SL-C",
    name: "Songle 5V 10A SPDT Miniature Power Relay",
    description: "Songle PCB subminiature sugar cube power relay 5V coil SPDT 10A 250VAC / 30VDC switching.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Songle Relay",
      coilVoltage: "5V DC",
      contactForm: "1 Form C (SPDT: 1 NO, 1 NC)",
      contactRating: "10A 250VAC / 10A 30VDC",
      packageFootprint: "PCB 5-Pin Through-Hole (19x15.5x15.5mm)",
    },
  },
];

export const seedDatabase = async () => {
  console.log(`Seeding ${realWorldElectronicsCatalog.length} realistic components into master items catalog...`);

  for (const item of realWorldElectronicsCatalog) {
    await db
      .insert(itemsTable)
      .values(item)
      .onConflictDoUpdate({
        target: itemsTable.partNumber,
        set: {
          name: item.name,
          description: item.description,
          category: item.category,
          unit: item.unit,
          specifications: item.specifications,
          updatedAt: new Date(),
        },
      });
  }

  console.log(`✅ Successfully seeded ${realWorldElectronicsCatalog.length} components with real manufacturers, modules, sensors, and displays!`);
};

seedDatabase()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seeding failed:", err);
    process.exit(1);
  });
