import { db, itemsTable } from "../src/db/index.js";

const realWorldElectronicsCatalog = [
  {
    partNumber: "ESP32-WROOM-32E-N4",
    name: "Espressif ESP32-WROOM-32E 4MB Flash Module",
    description: "Espressif 240MHz dual-core Xtensa 32-bit LX6 with integrated 4MB SPI flash and PCB trace antenna.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Espressif Systems",
      architecture: "Xtensa Dual-Core 32-bit LX6",
      clockSpeed: "240 MHz",
      flashSize: "4 MB",
      sramSize: "520 KB",
      wireless: "Wi-Fi 802.11 b/g/n + Bluetooth 4.2 / BLE",
      voltage: "3.0V - 3.6V",
      packageFootprint: "SMD Module 38-Pin (18x25.5mm)",
    },
  },
  {
    partNumber: "ESP32-WROOM-32E-N8",
    name: "Espressif ESP32-WROOM-32E 8MB Flash Module",
    description: "Espressif 240MHz dual-core Xtensa 32-bit LX6 with extended 8MB SPI flash for larger OTA partitions.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Espressif Systems",
      architecture: "Xtensa Dual-Core 32-bit LX6",
      clockSpeed: "240 MHz",
      flashSize: "8 MB",
      sramSize: "520 KB",
      wireless: "Wi-Fi 802.11 b/g/n + Bluetooth 4.2 / BLE",
      voltage: "3.0V - 3.6V",
      packageFootprint: "SMD Module 38-Pin (18x25.5mm)",
    },
  },
  {
    partNumber: "ESP32-S3-WROOM-1-N8R8",
    name: "Espressif ESP32-S3 AI Vector MCU 8MB Flash 8MB PSRAM",
    description: "Espressif dual-core Xtensa LX7 MCU with vector instructions for AI acceleration, 8MB Quad SPI Flash and 8MB Octal PSRAM.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Espressif Systems",
      architecture: "Xtensa Dual-Core 32-bit LX7 with Vector Extensions",
      clockSpeed: "240 MHz",
      flashSize: "8 MB",
      psramSize: "8 MB (Octal)",
      sramSize: "512 KB",
      wireless: "Wi-Fi 802.11 b/g/n (2.4GHz) + Bluetooth 5 (LE)",
      packageFootprint: "SMD Module 41-Pin (18x25.5mm)",
    },
  },
  {
    partNumber: "ESP32-C3-WROOM-02-N4",
    name: "Espressif ESP32-C3 RISC-V 32-bit Single-Core MCU",
    description: "Espressif cost-optimized 160MHz single-core 32-bit RISC-V microcontroller with 4MB embedded Flash.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Espressif Systems",
      architecture: "32-bit RISC-V Single-Core (RV32IMC)",
      clockSpeed: "160 MHz",
      flashSize: "4 MB",
      sramSize: "400 KB",
      wireless: "Wi-Fi 802.11 b/g/n + Bluetooth 5 (LE)",
      packageFootprint: "SMD Module 18-Pin (18x20mm)",
    },
  },
  {
    partNumber: "STM32F103C8T6",
    name: "STMicroelectronics STM32F103C8T6 ARM Cortex-M3 72MHz MCU",
    description: "STMicroelectronics mainstream performance line ARM Cortex-M3 32-bit MCU with 64KB Flash in LQFP-48.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      core: "ARM Cortex-M3",
      clockSpeed: "72 MHz",
      flashMemory: "64 KB",
      sram: "20 KB",
      interfaces: "2x SPI, 2x I2C, 3x USART, 1x USB 2.0 Full-Speed, 1x CAN 2.0B",
      packageFootprint: "LQFP-48 (7x7mm)",
      voltage: "2.0V - 3.6V",
    },
  },
  {
    partNumber: "STM32F401RET6",
    name: "STMicroelectronics STM32F401RE ARM Cortex-M4 84MHz MCU",
    description: "STMicroelectronics dynamic efficiency line ARM Cortex-M4 MCU with FPU, 512KB Flash, 96KB SRAM in LQFP-64.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      core: "ARM Cortex-M4 with FPU",
      clockSpeed: "84 MHz",
      flashMemory: "512 KB",
      sram: "96 KB",
      interfaces: "3x SPI, 3x I2C, 3x USART, 1x USB 2.0 OTG FS",
      packageFootprint: "LQFP-64 (10x10mm)",
      voltage: "1.7V - 3.6V",
    },
  },
  {
    partNumber: "STM32F411CEU6",
    name: "STMicroelectronics STM32F411CE ARM Cortex-M4 100MHz MCU",
    description: "STMicroelectronics high performance ARM Cortex-M4 MCU with 512KB Flash and 128KB SRAM in compact UFQFPN-48.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      core: "ARM Cortex-M4 with FPU",
      clockSpeed: "100 MHz",
      flashMemory: "512 KB",
      sram: "128 KB",
      packageFootprint: "UFQFPN-48 (7x7mm)",
      voltage: "1.7V - 3.6V",
    },
  },
  {
    partNumber: "ATMEGA328P-PU",
    name: "Microchip ATmega328P DIP-28 8-Bit AVR Microcontroller",
    description: "Microchip 20MHz 8-bit AVR RISC microcontroller with 32KB ISP Flash memory in DIP-28 through-hole package.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Microchip Technology",
      architecture: "8-bit AVR RISC",
      clockSpeed: "20 MHz",
      flashMemory: "32 KB",
      sram: "2 KB",
      eeprom: "1 KB",
      gpioCount: 23,
      adcChannels: 6,
      packageFootprint: "DIP-28",
      voltage: "1.8V - 5.5V",
    },
  },
  {
    partNumber: "ATMEGA328P-AU",
    name: "Microchip ATmega328P TQFP-32 8-Bit AVR Microcontroller",
    description: "Microchip 20MHz 8-bit AVR RISC microcontroller with 32KB ISP Flash in compact 32-lead surface mount TQFP package.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Microchip Technology",
      architecture: "8-bit AVR RISC",
      clockSpeed: "20 MHz",
      flashMemory: "32 KB",
      sram: "2 KB",
      eeprom: "1 KB",
      gpioCount: 23,
      adcChannels: 8,
      packageFootprint: "TQFP-32 (7x7mm)",
      voltage: "1.8V - 5.5V",
    },
  },
  {
    partNumber: "RP2040",
    name: "Raspberry Pi RP2040 Dual ARM Cortex-M0+ Microcontroller",
    description: "Raspberry Pi Foundation designed 133MHz dual-core ARM Cortex-M0+ microcontroller with 264KB internal SRAM and 8 PIO state machines.",
    category: "Microcontroller",
    unit: "pcs",
    specifications: {
      manufacturer: "Raspberry Pi Foundation",
      cores: "Dual ARM Cortex-M0+",
      clockSpeed: "133 MHz",
      sram: "264 KB",
      pioBlocks: "2x PIO state machines (8 total)",
      interfaces: "2x UART, 2x SPI, 2x I2C, 16x PWM, USB 1.1 Host/Device",
      packageFootprint: "QFN-56 (7x7mm)",
      voltage: "1.8V - 3.3V",
    },
  },
  {
    partNumber: "RC0805FR-0710KL",
    name: "Yageo 10k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 10kΩ ±1% 0.125W.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "10k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±100 ppm/°C",
    },
  },
  {
    partNumber: "CRCW080510K0FKEA",
    name: "Vishay Dale 10k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Vishay Dale commercial thick film surface mount chip resistor 10kΩ ±1% 0.125W automotive qualified AEC-Q200.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Vishay Dale",
      resistance: "10k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±100 ppm/°C",
      qualification: "AEC-Q200",
    },
  },
  {
    partNumber: "ERJ-6GEYJ103V",
    name: "Panasonic 10k Ohm 5% 1/8W SMD Resistor 0805",
    description: "Panasonic ERJ series thick film chip resistor 10kΩ ±5% 0.125W.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Panasonic",
      resistance: "10k Ohm",
      tolerance: "±5%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±200 ppm/°C",
    },
  },
  {
    partNumber: "RC0603FR-0710KL",
    name: "Yageo 10k Ohm 1% 1/10W SMD Resistor 0603",
    description: "Yageo RC0603 series miniature thick film surface mount chip resistor 10kΩ ±1% 0.1W in 0603 package.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "10k Ohm",
      tolerance: "±1%",
      powerRating: "0.1W (1/10W)",
      packageFootprint: "0603 (1608 Metric)",
      tempCoeff: "±100 ppm/°C",
    },
  },
  {
    partNumber: "MFR-25FRF52-10K",
    name: "Yageo 10k Ohm 1% 1/4W Metal Film Resistor Axial",
    description: "Yageo MFR series high precision metal film through-hole axial leaded resistor 10kΩ ±1% 0.25W.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "10k Ohm",
      tolerance: "±1%",
      powerRating: "0.25W (1/4W)",
      packageFootprint: "Axial Leaded (DO-41 size)",
      tempCoeff: "±50 ppm/°C",
    },
  },
  {
    partNumber: "RC0805FR-071KL",
    name: "Yageo 1k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 1kΩ ±1% 0.125W.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "1k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±100 ppm/°C",
    },
  },
  {
    partNumber: "CRCW08051K00FKEA",
    name: "Vishay Dale 1k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Vishay Dale thick film surface mount chip resistor 1kΩ ±1% 0.125W AEC-Q200.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Vishay Dale",
      resistance: "1k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
      tempCoeff: "±100 ppm/°C",
    },
  },
  {
    partNumber: "RC0805FR-07220RL",
    name: "Yageo 220 Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 220Ω ±1% 0.125W for LED current limiting.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "220 Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "RC0805FR-07100KL",
    name: "Yageo 100k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 100kΩ ±1% 0.125W pull-up resistor.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "100k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "RC0805FR-074K7L",
    name: "Yageo 4.7k Ohm 1% 1/8W SMD Resistor 0805",
    description: "Yageo RC0805 series thick film surface mount chip resistor 4.7kΩ ±1% 0.125W standard I2C bus pull-up.",
    category: "Resistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      resistance: "4.7k Ohm",
      tolerance: "±1%",
      powerRating: "0.125W (1/8W)",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "CL21B106KOQNNNE",
    name: "Samsung 10uF 16V X7R Ceramic Capacitor 0805",
    description: "Samsung Electro-Mechanics multi-layer ceramic chip capacitor (MLCC) 10µF 16V ±10% X7R.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Samsung Electro-Mechanics",
      capacitance: "10 uF",
      voltageRating: "16V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "GRM21BR71C106KE51L",
    name: "Murata 10uF 16V X7R Ceramic Capacitor 0805",
    description: "Murata GRM series multi-layer ceramic chip capacitor (MLCC) 10µF 16V ±10% X7R.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Murata Electronics",
      capacitance: "10 uF",
      voltageRating: "16V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "C2012X7R1C106K125AC",
    name: "TDK 10uF 16V X7R Ceramic Capacitor 0805",
    description: "TDK commercial grade multi-layer ceramic chip capacitor 10µF 16V ±10% X7R in 0805 package.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "TDK Corporation",
      capacitance: "10 uF",
      voltageRating: "16V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "CC0805KRX7R9BB104",
    name: "Yageo 100nF (0.1uF) 50V X7R Ceramic Capacitor 0805",
    description: "Yageo surface mount ceramic chip capacitor 0.1µF 50V ±10% X7R for IC power rail decoupling.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      capacitance: "100 nF (0.1 uF)",
      voltageRating: "50V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "C0805C104K5RACTU",
    name: "KEMET 100nF (0.1uF) 50V X7R Ceramic Capacitor 0805",
    description: "KEMET surface mount commercial grade MLCC 0.1µF 50V ±10% X7R in 0805 package.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "KEMET",
      capacitance: "100 nF (0.1 uF)",
      voltageRating: "50V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "CC0603KRX7R9BB104",
    name: "Yageo 100nF (0.1uF) 50V X7R Ceramic Capacitor 0603",
    description: "Yageo compact surface mount ceramic chip capacitor 0.1µF 50V ±10% X7R in 0603 footprint.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      capacitance: "100 nF (0.1 uF)",
      voltageRating: "50V DC",
      dielectric: "X7R",
      tolerance: "±10%",
      packageFootprint: "0603 (1608 Metric)",
    },
  },
  {
    partNumber: "UVP1E101MPD",
    name: "Nichicon 100uF 25V Radial Electrolytic Capacitor",
    description: "Nichicon VP series bi-polarized aluminum electrolytic capacitor 100µF 25V 20% radial leaded.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Nichicon",
      capacitance: "100 uF",
      voltageRating: "25V DC",
      tolerance: "±20%",
      packageFootprint: "Radial Can (8x11.5mm, 5mm Pitch)",
    },
  },
  {
    partNumber: "EEU-FR1E101",
    name: "Panasonic 100uF 25V Low ESR Radial Electrolytic Capacitor",
    description: "Panasonic FR series ultra-low ESR long life aluminum electrolytic capacitor 100µF 25V 20% radial leaded.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Panasonic",
      capacitance: "100 uF",
      voltageRating: "25V DC",
      tolerance: "±20%",
      esr: "0.08 Ohm (Low ESR)",
      lifetime: "6000 Hrs @ 105°C",
      packageFootprint: "Radial Can (6.3x11.2mm)",
    },
  },
  {
    partNumber: "CC0805JRNPO9BN220",
    name: "Yageo 22pF 50V C0G/NP0 Ceramic Capacitor 0805",
    description: "Yageo ultra-stable C0G/NP0 dielectric ceramic capacitor 22pF 50V ±5% for 16MHz/32MHz crystal oscillators.",
    category: "Capacitor",
    unit: "pcs",
    specifications: {
      manufacturer: "Yageo",
      capacitance: "22 pF",
      voltageRating: "50V DC",
      dielectric: "C0G / NP0",
      tolerance: "±5%",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "1N4007-TP",
    name: "MCC 1N4007 1A 1000V Standard Recovery Rectifier Diode",
    description: "Micro Commercial Co standard recovery power rectifier diode 1A 1000V in axial leaded DO-41 package.",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "Micro Commercial Components (MCC)",
      diodeType: "Standard Recovery Rectifier",
      forwardCurrent: "1A",
      peakReverseVoltage: "1000V",
      forwardVoltageDrop: "1.1V @ 1A",
      packageFootprint: "DO-41 Axial",
    },
  },
  {
    partNumber: "1N4007-E3/54",
    name: "Vishay 1N4007 1A 1000V Standard Rectifier Diode",
    description: "Vishay General Semiconductor standard recovery 1A 1000V rectifier diode in DO-204AL (DO-41).",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "Vishay General Semiconductor",
      forwardCurrent: "1A",
      peakReverseVoltage: "1000V",
      packageFootprint: "DO-41 Axial",
    },
  },
  {
    partNumber: "S1M-13-F",
    name: "Diodes Inc S1M 1A 1000V Surface Mount Rectifier Diode SMA",
    description: "Diodes Incorporated 1A 1000V surface mount equivalent of 1N4007 in compact SMA (DO-214AC) package.",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "Diodes Incorporated",
      forwardCurrent: "1A",
      peakReverseVoltage: "1000V",
      packageFootprint: "SMA (DO-214AC)",
    },
  },
  {
    partNumber: "1N4148WS-7-F",
    name: "Diodes Inc 1N4148WS 100V 300mA High-Speed Switching Diode",
    description: "Diodes Incorporated fast switching surface mount diode 100V 300mA 4ns recovery time in SOD-323.",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "Diodes Incorporated",
      diodeType: "High Speed Switching",
      reverseVoltage: "100V",
      forwardCurrent: "300mA",
      reverseRecoveryTime: "4 ns",
      packageFootprint: "SOD-323",
    },
  },
  {
    partNumber: "1N4148-T50A",
    name: "onsemi 1N4148 100V 200mA Fast Switching Diode Axial",
    description: "ON Semiconductor fast switching through-hole signal diode 100V 200mA in DO-35 glass package.",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "onsemi",
      diodeType: "Fast Switching Diode",
      reverseVoltage: "100V",
      forwardCurrent: "200mA",
      packageFootprint: "DO-35 Axial Glass",
    },
  },
  {
    partNumber: "B5819W-TP",
    name: "MCC 1N5819 (B5819W) 1A 40V Schottky Barrier Diode SOD-123",
    description: "Micro Commercial Co 1A 40V low forward voltage drop Schottky barrier diode in SOD-123 for reverse polarity protection.",
    category: "Diode",
    unit: "pcs",
    specifications: {
      manufacturer: "Micro Commercial Components (MCC)",
      diodeType: "Schottky Barrier",
      forwardCurrent: "1A",
      reverseVoltage: "40V",
      forwardVoltageDrop: "0.45V @ 1A (Low Drop)",
      packageFootprint: "SOD-123",
    },
  },
  {
    partNumber: "150080RS75000",
    name: "Würth Elektronik Red SMD LED 0805 Clear Lens",
    description: "Würth Elektronik WL-SMCW series red surface mount chip LED 625nm 120mcd 0805.",
    category: "LED",
    unit: "pcs",
    specifications: {
      manufacturer: "Würth Elektronik",
      color: "Red",
      dominantWavelength: "625 nm",
      forwardVoltage: "2.0V",
      forwardCurrent: "20 mA",
      luminousIntensity: "120 mcd",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "150080GS75000",
    name: "Würth Elektronik Green SMD LED 0805 Clear Lens",
    description: "Würth Elektronik WL-SMCW series green surface mount chip LED 525nm 260mcd 0805.",
    category: "LED",
    unit: "pcs",
    specifications: {
      manufacturer: "Würth Elektronik",
      color: "Green",
      dominantWavelength: "525 nm",
      forwardVoltage: "3.2V",
      forwardCurrent: "20 mA",
      luminousIntensity: "260 mcd",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "150080BS75000",
    name: "Würth Elektronik Blue SMD LED 0805 Clear Lens",
    description: "Würth Elektronik WL-SMCW series blue surface mount chip LED 470nm 140mcd 0805.",
    category: "LED",
    unit: "pcs",
    specifications: {
      manufacturer: "Würth Elektronik",
      color: "Blue",
      dominantWavelength: "470 nm",
      forwardVoltage: "3.2V",
      forwardCurrent: "20 mA",
      luminousIntensity: "140 mcd",
      packageFootprint: "0805 (2012 Metric)",
    },
  },
  {
    partNumber: "WP7113ID",
    name: "Kingbright 5mm Red Through-Hole LED Diffused",
    description: "Kingbright 5mm round diffused red through-hole indicator LED 625nm 2.0V 20mA.",
    category: "LED",
    unit: "pcs",
    specifications: {
      manufacturer: "Kingbright",
      color: "Red",
      diameter: "5.0 mm (T-1 3/4)",
      forwardVoltage: "2.0V",
      forwardCurrent: "20 mA",
      packageFootprint: "Radial 5mm Through-Hole",
    },
  },
  {
    partNumber: "AMS1117-3.3",
    name: "Advanced Monolithic Systems AMS1117 3.3V 1A LDO Regulator",
    description: "AMS1117 series low dropout positive voltage regulator fixed 3.3V 1A output in SOT-223.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Advanced Monolithic Systems",
      regulatorType: "LDO Linear Voltage Regulator",
      outputVoltage: "3.3V Fixed",
      maxOutputCurrent: "1.0A",
      dropoutVoltage: "1.3V @ 1A",
      maxInputVoltage: "15V",
      packageFootprint: "SOT-223",
    },
  },
  {
    partNumber: "AZ1117EH-3.3TRG1",
    name: "Diodes Inc AZ1117E 3.3V 1A Low Dropout Regulator",
    description: "Diodes Incorporated low dropout linear regulator 3.3V 1A with thermal shutdown in SOT-223.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Diodes Incorporated",
      outputVoltage: "3.3V Fixed",
      maxOutputCurrent: "1.0A",
      packageFootprint: "SOT-223",
    },
  },
  {
    partNumber: "LM7805CT",
    name: "Texas Instruments LM7805 5V 1.5A Positive Linear Regulator",
    description: "Texas Instruments 3-terminal positive voltage regulator 5.0V 1.5A in TO-220 package.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Texas Instruments",
      outputVoltage: "5.0V Fixed",
      maxOutputCurrent: "1.5A",
      maxInputVoltage: "35V",
      packageFootprint: "TO-220-3",
    },
  },
  {
    partNumber: "L7805CV",
    name: "STMicroelectronics L7805 5V 1.5A Linear Regulator",
    description: "STMicroelectronics positive voltage regulator 5.0V 1.5A with internal current limiting and thermal overload protection in TO-220.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      outputVoltage: "5.0V Fixed",
      maxOutputCurrent: "1.5A",
      packageFootprint: "TO-220-3",
    },
  },
  {
    partNumber: "2N7002-7-F",
    name: "Diodes Inc 2N7002 60V 115mA N-Channel MOSFET SOT-23",
    description: "Diodes Incorporated N-Channel enhancement mode field effect transistor 60V 115mA in SOT-23.",
    category: "Transistor",
    unit: "pcs",
    specifications: {
      manufacturer: "Diodes Incorporated",
      transistorType: "N-Channel MOSFET",
      drainSourceVoltage: "60V",
      continuousDrainCurrent: "115 mA",
      rdsOn: "7.5 Ohm @ 10V",
      packageFootprint: "SOT-23-3",
    },
  },
  {
    partNumber: "2N7002LT1G",
    name: "onsemi 2N7002 60V 115mA N-Channel MOSFET SOT-23",
    description: "ON Semiconductor small signal N-Channel MOSFET 60V 115mA in SOT-23-3 package.",
    category: "Transistor",
    unit: "pcs",
    specifications: {
      manufacturer: "onsemi",
      transistorType: "N-Channel MOSFET",
      drainSourceVoltage: "60V",
      continuousDrainCurrent: "115 mA",
      packageFootprint: "SOT-23-3",
    },
  },
  {
    partNumber: "BME280",
    name: "Bosch Sensortec BME280 Temp, Humidity & Pressure Sensor",
    description: "Bosch Sensortec high precision digital environmental sensor with I2C and SPI interfaces in LGA-8 package.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Bosch Sensortec",
      measuredParameters: "Temperature, Relative Humidity, Barometric Pressure",
      humidityRange: "0% to 100% RH (±3%)",
      pressureRange: "300 to 1100 hPa (±1 hPa)",
      temperatureRange: "-40°C to 85°C (±0.5°C)",
      interface: "I2C and SPI",
      packageFootprint: "LGA-8 (2.5x2.5mm)",
    },
  },
  {
    partNumber: "BMP280",
    name: "Bosch Sensortec BMP280 Barometric Pressure & Temp Sensor",
    description: "Bosch Sensortec compact digital barometric pressure and temperature sensor with I2C/SPI interfaces.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Bosch Sensortec",
      measuredParameters: "Barometric Pressure, Temperature",
      pressureRange: "300 to 1100 hPa (±1 hPa)",
      temperatureRange: "-40°C to 85°C",
      interface: "I2C and SPI",
      packageFootprint: "LGA-8 (2.0x2.5mm)",
    },
  },
  {
    partNumber: "DHT22",
    name: "Aosong DHT22 (AM2302) Digital Temp & Humidity Sensor",
    description: "Aosong capacitive humidity and thermistor temperature sensor module with single-wire digital interface.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Aosong Electronics",
      humidityRange: "0% - 99.9% RH (±2%)",
      temperatureRange: "-40°C to 80°C (±0.5°C)",
      samplingRate: "0.5 Hz",
      voltage: "3.3V - 5.5V",
      packageFootprint: "4-Pin Module",
    },
  },
  {
    partNumber: "SHT31-DIS-B",
    name: "Sensirion SHT31-DIS High Accuracy Humidity & Temp Sensor",
    description: "Sensirion high accuracy digital humidity and temperature sensor with I2C interface in DFN-8 package.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "Sensirion",
      humidityAccuracy: "±2% RH",
      temperatureAccuracy: "±0.2°C",
      interface: "I2C with selectable address",
      voltage: "2.15V - 5.5V",
      packageFootprint: "DFN-8 (2.5x2.5mm)",
    },
  },
  {
    partNumber: "MPU-6050",
    name: "TDK InvenSense MPU-6050 6-Axis MotionTracking IMU",
    description: "TDK InvenSense 6-axis MotionTracking device combining a 3-axis gyroscope and a 3-axis accelerometer with I2C Digital Motion Processor (DMP).",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "TDK InvenSense",
      sensorType: "6-Axis IMU (3-Axis Gyro + 3-Axis Accel)",
      gyroRange: "±250, ±500, ±1000, ±2000 °/sec",
      accelRange: "±2g, ±4g, ±8g, ±16g",
      interface: "I2C",
      packageFootprint: "QFN-24 (4x4mm)",
    },
  },
  {
    partNumber: "LSM6DS3TR-C",
    name: "STMicroelectronics LSM6DS3 6-Axis iNEMO Inertial Module",
    description: "STMicroelectronics ultra-low-power high-performance 3-axis digital accelerometer and 3-axis digital gyroscope in LGA-14.",
    category: "Sensor",
    unit: "pcs",
    specifications: {
      manufacturer: "STMicroelectronics",
      sensorType: "6-Axis IMU",
      gyroRange: "±125 to ±2000 dps",
      accelRange: "±2g to ±16g",
      interface: "SPI / I2C",
      packageFootprint: "LGA-14 (2.5x3.0mm)",
    },
  },
  {
    partNumber: "TYPE-C-31-M-12",
    name: "Korean Hroparts 16-Pin USB Type-C Receptacle Hybrid SMD/THT",
    description: "Korean Hroparts 16-pin USB Type-C female connector with mid-mount SMD pins and 4 through-hole shielding retention legs.",
    category: "Connector",
    unit: "pcs",
    specifications: {
      manufacturer: "Korean Hroparts Electronics",
      connectorType: "USB Type-C Female Receptacle",
      pinCount: 16,
      currentRating: "3.0A",
      voltageRating: "20V DC",
      matingCycles: "10,000 Cycles",
      packageFootprint: "Hybrid SMD + 4 THT Shell Posts",
    },
  },
  {
    partNumber: "105450-0101",
    name: "Molex Universal USB Type-C Receptacle Dual-Row SMT",
    description: "Molex standard USB Type-C female connector dual-row surface mount with 4 solder tabs.",
    category: "Connector",
    unit: "pcs",
    specifications: {
      manufacturer: "Molex",
      connectorType: "USB Type-C Receptacle",
      pinCount: 24,
      currentRating: "5.0A",
      voltageRating: "30V DC",
      packageFootprint: "Dual Row SMT",
    },
  },
  {
    partNumber: "61304011121",
    name: "Würth Elektronik 40-Pin 2.54mm Breakaway Pin Header Male",
    description: "Würth Elektronik WR-PHD series 2.54mm pitch 40-pin single row straight through-hole male pin header strip.",
    category: "Connector",
    unit: "pcs",
    specifications: {
      manufacturer: "Würth Elektronik",
      pitch: "2.54 mm (0.1 inch)",
      numberOfPositions: 40,
      contactPlating: "Gold Plated",
      currentRating: "3.0A",
      packageFootprint: "Through-Hole Vertical",
    },
  },
  {
    partNumber: "B3F-1000",
    name: "Omron 6x6mm SPST Tactile Push Button Switch",
    description: "Omron Electronics B3F series 6x6x4.3mm miniature tactile push button switch SPST-NO through-hole.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Omron Electronics",
      switchFunction: "Momentary SPST-NO",
      operatingForce: "0.98 N (100 gf)",
      contactRating: "50 mA @ 24V DC",
      mechanicalLife: "1,000,000 Operations",
      packageFootprint: "Through-Hole 4-Pin (6.0x6.0mm)",
    },
  },
  {
    partNumber: "CH340C",
    name: "WCH CH340C USB to UART Serial Bridge IC Internal Oscillator",
    description: "Jiangsu Qinheng Microelectronics (WCH) USB to serial UART interface converter with internal clock generator in SOP-16.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "WCH (Jiangsu Qinheng Microelectronics)",
      function: "USB 2.0 Full-Speed to UART Serial Bridge",
      clockSource: "Internal Oscillator (No external crystal needed)",
      baudRate: "50 bps to 2 Mbps",
      packageFootprint: "SOP-16 (150mil)",
    },
  },
  {
    partNumber: "CP2102N-A02-GQFN28",
    name: "Silicon Labs CP2102N USBXpress USB-to-UART Bridge QFN-28",
    description: "Silicon Laboratories highly integrated USB 2.0 Full-Speed to UART bridge controller in 5x5mm QFN-28.",
    category: "IC",
    unit: "pcs",
    specifications: {
      manufacturer: "Silicon Labs",
      function: "USB 2.0 to UART Controller",
      baudRate: "Up to 3 Mbps",
      packageFootprint: "QFN-28 (5x5mm)",
    },
  },
  {
    partNumber: "SRD-05VDC-SL-C",
    name: "Songle 5V 10A SPDT Miniature Power Relay",
    description: "Songle PCB subminiature sugar cube power relay 5V coil SPDT 10A 250VAC / 30VDC switching.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Songle Relay",
      coilVoltage: "5V DC",
      contactForm: "1 Form C (SPDT: 1 NO, 1 NC)",
      contactRating: "10A 250VAC / 10A 30VDC",
      packageFootprint: "PCB 5-Pin Through-Hole (19x15.5x15.5mm)",
    },
  },
  {
    partNumber: "G5Q-14-DC5",
    name: "Omron 5V 10A SPDT Miniature Power Relay High Sensitivity",
    description: "Omron G5Q series compact PCB power relay 5V coil SPDT 10A 250VAC switching with 8kV surge withstand voltage.",
    category: "Other",
    unit: "pcs",
    specifications: {
      manufacturer: "Omron Electronics",
      coilVoltage: "5V DC",
      contactRating: "10A @ 250V AC",
      packageFootprint: "PCB 5-Pin Through-Hole",
    },
  },
];

export const seedDatabase = async () => {
  console.log(`Seeding ${realWorldElectronicsCatalog.length} realistic components into master items catalog...`);

  for (const item of realWorldElectronicsCatalog) {
    await db
      .insert(itemsTable)
      .values(item)
      .onConflictDoUpdate({
        target: itemsTable.partNumber,
        set: {
          name: item.name,
          description: item.description,
          category: item.category,
          unit: item.unit,
          specifications: item.specifications,
          updatedAt: new Date(),
        },
      });
  }

  console.log(`✅ Successfully seeded ${realWorldElectronicsCatalog.length} components with real manufacturers & multiple equivalent variants!`);
};

seedDatabase()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seeding failed:", err);
    process.exit(1);
  });
